### ISSUE TITLE
编译中出现Maven [ERROR] 不再支持源选项 5。请使用 6 或更高版本

### ISSUE THREAD

**Issue by 2077himasi** [c0ny1/chunked-coding-converter#3]
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>12</maven.compiler.source>
		<maven.compiler.target>12</maven.compiler.target>	
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

**Comment by 2077himasi** [comment]
修改pom.xml中的为
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>10</maven.compiler.source>
    <maven.compiler.target>10</maven.compiler.target>
</properties>

> UTF-8 12 12	UTF-8

**Comment by c0ny1** [comment]
1. 你是解决了这个问题对吧。
2. 在我这边maven编码没有出现该问题，能提供下你的jdk版本和maven版本么

**Comment by 2077himasi** [comment]
jdk10  apache-maven-3.6.1
环境win10

**Comment by c0ny1** [comment]
这个问题，每个人根据自己安装的jdk版自行修改吧
