### ISSUE TITLE
xml分块传输

### ISSUE THREAD

**Issue by newanx1ang** [c0ny1/chunked-coding-converter#6]
实际检测了一下 xml分块传输时将content type改为x-www-form-urlencoded就可以分块了，但是post数据太大貌似就不会分块 大佬能改改长度吗，至少让他传输个2729绕过的那个最大数据包的长度。

**Comment by newanx1ang** [comment]
已自己修改源码编译

**Comment by newanx1ang** [comment]
谢谢大佬

**Comment by c0ny1** [comment]
包体太大问题，可能会导致卡顿，后续修改。如果你已修复，可以提交pr。
